services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST:-localhost}
    ports:
      - "5432:${DB_PORT:-5432}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-job_board}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
